---
- name: Create users with SHA-512 hashed passwords
  hosts: all
  vars:
    users:
      - andy
  tasks:
    - name: Generate random password and salt for each user
      set_fact:
        user_credentials: "{{ user_credentials | default({}) | combine({item: {'plain_password': plain_password, 'salt': salt, 'hashed_password': hashed_password}}) }}"
      vars:
        plain_password: "{{ 48 | random | password_hash('sha512') }}"
        salt: "{{ 48 | random | password_hash('sha512') }}"
        hashed_password: "{{ (plain_password + salt) | password_hash('sha512') }}"
      with_items: "{{ users }}"
      loop_control:
        loop_var: item

    - name: Save the plain password and salt to a file for each user
      local_action:
        module: copy
        content: |
          Plain Password: {{ user_credentials[item].plain_password }}
          Salt: {{ user_credentials[item].salt }}
        dest: "{{ item }}-password.txt"
      with_items: "{{ users }}"
      loop_control:
        loop_var: item

    - name: Create a user with the hashed password
      user:
        name: "{{ item }}"
        password: "{{ user_credentials[item].hashed_password }}"
        update_password: always
      with_items: "{{ users }}"
      loop_control:
        loop_var: item

    - name: Debug the generated values for each user
      debug:
        msg:
          user: "{{ item }}"
          plain_password: "{{ user_credentials[item].plain_password }}"
          salt: "{{ user_credentials[item].salt }}"
          hashed_password: "{{ user_credentials[item].hashed_password }}"
      with_items: "{{ users }}"
      loop_control:
        loop_var: item
