---
- name: Installs nginx web server and uses certbot to install ssl cert
  hosts: all
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
    
    # - name: Remove default nginx config
    #   file: name=/etc/nginx/sites-enabled/default state=absent

    # - name: Install system nginx config
    #   template:
    #     src: templates/nginx.conf.j2
    #     dest: /etc/nginx/nginx.conf

    # - name: Install nginx site for letsencrypt requests
    #   template:
    #     src: templates/nginx-http.j2
    #     dest: /etc/nginx/sites-enabled/{{ domain_name }}.http
    #   loop: "{{ domain_names }}"
    #   loop_control:
    #     loop_var: domain_name

    - name: create websever domain folders
      file:
        name: /var/www/{{ domain_name }}
        state: directory
      loop: "{{ domain_names }}"
      loop_control:
        loop_var: domain_name

    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    - name: Installs certbot and uses it to create an SSL and enabled https
      block:
        - name: Install certbot
          command: snap install --classic certbot

        - name: Prepare the certbot command
          file:
            state: link
            src: /snap/bin/certbot
            dest: /usr/bin/certbot
        
        - name: testing map regex filter 
          debug:
            msg: "{{ domain_names | map('regex_replace', '^(.*)$', '-w /var/www/\\1 -d \\1') | join(' ') }}"

        - name: Run certbot to create certs and enable on nginx
          command: certbot --agree-tos --email {{ email }} --nginx -n {{ domain_names | map('regex_replace', '^(.*)$', '-w /var/www/\\1 -d \\1') | join(' ') }} --expand
        
        - name: Restart nginx
          service:
            name: nginx
            state: restarted


            